### ISSUE TITLE
ARIN XML Parsing

### ISSUE THREAD

**Issue by SchellerCyberSecurity** [leebaird/discover#160]
Receiving the below error when running the updated discover script.

`ARIN
     Email                (2/48)
     Names                (3/48)
     Networks             (4/48)
tmp.xml:58: parser error : Opening and ending tag mismatch: base line 57 and head
</head>
       ^
tmp.xml:67: parser error : Opening and ending tag mismatch: input line 57 and span
t id="whoisSubmitButton" type="submit" name="whoisSubmitButton" value=" "></span
                                                                               ^
tmp.xml:68: parser error : Opening and ending tag mismatch: span line 57 and form
</form>
       ^
tmp.xml:70: parser error : Opening and ending tag mismatch: input line 57 and fieldset
</fieldset>
           ^
tmp.xml:71: parser error : Opening and ending tag mismatch: input line 57 and div
</div>
      ^
tmp.xml:111: parser error : Opening and ending tag mismatch: input line 57 and div
</div>
      ^
tmp.xml:141: parser error : Entity 'copy' not defined
            &copy; Copyright 1997 - 2019, American Registry for Internet Numbers
                  ^
tmp.xml:141: parser error : Opening and ending tag mismatch: br line 57 and p
   &copy; Copyright 1997 - 2019, American Registry for Internet Numbers, Ltd.</p
                                                                               ^
tmp.xml:142: parser error : Opening and ending tag mismatch: p line 57 and div
</div>
      ^
tmp.xml:143: parser error : Opening and ending tag mismatch: div line 57 and body
</body>
       ^
tmp.xml:144: parser error : Opening and ending tag mismatch: form line 57 and html
</html>
       ^
tmp.xml:145: parser error : EndTag: '</' not found

^
grep: tmp2: No such file or directory`

**Comment by leebaird** [comment]
A simple git pull should resolve the issue.

**Comment by joacole** [comment]
I'm having the same issue and doing a pull didn't resolve the issue. I also nuked the /opt/discover directory and did a new clone from the repo.
