### ISSUE TITLE
Shell Script files failing on new install/Upgrde

### ISSUE THREAD

**Issue by Johnthe0n** [leebaird/discover#214]
After beating my head against the table for some time, I have found that the Shell Script files for disover.sh, domian.sh, generateTargets.sh, nikto.sh, parse.sh, and payload.sh are missing the period between the lines ( "$DISCOVER"/whatever.sh ;; ) where the old and correct code was                           ( "$DISCOVER"./whatever.sh ;; ) I have gone through all the shell scripts and changed them all for my use but the issue exists when you update in Debian Linux and gives a "you cant get there from here" kinda error... Just giving ya a heads up

**Comment by L1ghtn1ng** [comment]
@Johnthe0n Should be fixed in master now if you can give it a retry please?

**Comment by L1ghtn1ng** [comment]
I had to revert it, as things broke when doing your changes, things seem to work correctly when I reverted it, can you try a complete new clone of the repo please as something on your end seems a little wonky for some reason, just trying to wrap my head around your issue

**Comment by Johnthe0n** [comment]
I just deleted and did a full new clone of the repo, here is the error I am still getting when trying to just setup via the update file attached. I can resolve all of these running nano I know it just makes me want to kick a tesla having to go through all the code. 

![Image](https://github.com/user-attachments/assets/96491e41-7c06-413a-b3b7-8567eb4962ee)
